{
 "title": "Snapraid",
 "description": "Show Snapraid Metrics using snapraid-collector\nhttps://github.com/ljmerza/snapraid-collector",
 "tags": [
  "snapraid",
  "smart"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SMART", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Ran",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_smart_last_ran", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Fail Probability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snapraid_smart_total_fail_probability",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snapraid_smart_disk_error_count",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk Fail Probability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "snapraid_smart_disk_fail_probability",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk Power On",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "snapraid_smart_disk_power_on_days",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "snapraid_smart_disk_temperature",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Last Ran",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_sync_last_ran", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "File Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_sync_file_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IO Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_sync_io_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_sync_data_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scan Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "targets": [
    {
     "expr": "snapraid_sync_scan_time_seconds",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Accessed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_sync_accessed_mb", "legendFormat": "__auto" }
   ]
  },
  { "title": "Scrub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Last Ran",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_smart_last_ran", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "File Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_scrub_file_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_scrub_data_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IO Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snapraid_scrub_io_errors", "legendFormat": "__auto" }
   ]
  }
 ]
}